apiVersion: v1
kind: Service
metadata:
  name: django-banking-service
  labels:
    app: django-banking
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: django-banking 